version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
      - "9009:9009" # GRPC interface (optional)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse-server
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Define your own password
